INSERT INTO State (state_id, state_name, country_id) VALUES (35, 'Andaman And Nicobar Islands', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (28, 'Andhra Pradesh', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (12, 'Arunachal Pradesh', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (18, 'Assam', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (10, 'Bihar', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (4, 'Chandigarh', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (22, 'Chhattisgarh', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (7, 'Delhi', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (30, 'Goa', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (24, 'Gujarat', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (6, 'Haryana', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (2, 'Himachal Pradesh', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (1, 'Jammu And Kashmir', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (20, 'Jharkhand', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (29, 'Karnataka', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (32, 'Kerala', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (37, 'Ladakh', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (31, 'Lakshadweep', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (23, 'Madhya Pradesh', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (27, 'Maharashtra', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (14, 'Manipur', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (17, 'Meghalaya', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (15, 'Mizoram', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (13, 'Nagaland', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (21, 'Odisha', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (34, 'Puducherry', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (3, 'Punjab', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (8, 'Rajasthan', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (11, 'Sikkim', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (33, 'Tamil Nadu', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (36, 'Telangana', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (38, 'The Dadra And Nagar Haveli And Daman And Diu', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (16, 'Tripura', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (5, 'Uttarakhand', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (9, 'Uttar Pradesh', 1);
INSERT INTO State (state_id, state_name, country_id) VALUES (19, 'West Bengal', 1);