INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7024, 'Adhartal', 411);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3518, 'Agar', 667);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3435, 'Ajaygarh', 420);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3713, 'Alirajpur', 639);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3502, 'Alot', 423);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3439, 'Amanganj', 420);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3468, 'Amarpatan', 784);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3648, 'Amarwara', 399);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3385, 'Ambah', 417);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3605, 'Amla', 394);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3557, 'Anjad', 393);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3694, 'Anuppur', 390);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3682, 'Aron', 406);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3686, 'Ashoknagar', 391);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3584, 'Ashta', 427);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3391, 'Ater', 395);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3599, 'Athner', 394);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6510, 'Avantipur Barodia', 430);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6998, 'Badagaon (Dhasan)', 434);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3431, 'Bada Malhera', 398);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3412, 'Badarwas', 432);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3595, 'Badi', 421);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3514, 'Badnagar', 435);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3532, 'Badnawar', 403);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3517, 'Badod', 667);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3383, 'Badoda', 431);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3623, 'Badwara', 413);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3529, 'Bagli', 402);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6978, 'Bahadurpur', 391);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6072, 'Bahari', 433);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3625, 'Bahoriband', 413);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3674, 'Baihar', 392);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6534, 'Bairad', 432);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6071, 'Bajag', 404);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3505, 'Bajna', 423);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3672, 'Balaghat', 392);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3421, 'Baldeogarh', 434);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7112, 'Bamor', 417);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3678, 'Bamori', 406);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3446, 'Banda', 425);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7420, 'Bandari', 425);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3482, 'Bandhavgarh', 436);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3619, 'Bankhedi', 409);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3594, 'Baraily', 421);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7423, 'Bargawan', 638);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3665, 'Barghat', 428);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3622, 'Barhi', 413);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7001, 'Baroni', 401);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3545, 'Barwaha', 414);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3554, 'Barwani', 393);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3573, 'Basoda', 437);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3456, 'Batiyagarh', 400);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3381, 'Beerpur', 431);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3592, 'Begamganj', 421);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3689, 'Beohari', 429);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3580, 'Berasia', 396);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3600, 'Betul', 394);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6989, 'Betul Nagar', 394);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3552, 'Bhagwanpura', 414);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3598, 'Bhainsdehi', 394);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3587, 'Bhairunda', 427);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3406, 'Bhander', 401);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3492, 'Bhanpura', 416);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3549, 'Bhikangaon', 414);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7027, 'Bhimpur', 394);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3392, 'Bhind', 395);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6994, 'Bhind Nagar', 395);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3401, 'Bhitarwar', 407);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3566, 'Biaora', 422);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3645, 'Bichhiya', 415);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3657, 'Bichhua', 399);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7013, 'Bicholi Hapsi', 410);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3433, 'Bijawar', 398);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6974, 'Bilaspur', 436);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3443, 'Bina', 425);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7033, 'Birsa', 392);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3463, 'Birsinghpur', 426);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3588, 'Budni', 427);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3719, 'Burhanpur', 397);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6972, 'Burhanpur Nagar', 397);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6988, 'Burhar', 429);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3434, 'Buxwaha', 398);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3683, 'Chachaura', 406);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6996, 'Chand', 399);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3685, 'Chanderi', 391);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3483, 'Chandia', 436);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3426, 'Chandla', 398);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3711, 'Chandra Shekhar Azad Nagar', 639);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3650, 'Chaurai', 399);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7424, 'Chhaigaon Makhan', 405);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3660, 'Chhapara', 428);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3429, 'Chhatarpur', 398);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7006, 'Chhatarpur Nagar', 398);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3654, 'Chhindwara', 399);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7020, 'Chhindwara Nagar', 399);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3601, 'Chicholi', 394);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3402, 'Chinour', 407);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3703, 'Chitrangi', 638);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3698, 'Churhat', 433);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7039, 'City Center', 407);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3400, 'Dabra', 407);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3537, 'Dahi', 403);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3497, 'Daloda', 416);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3458, 'Damoh', 400);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6999, 'Damyanti Nagar', 400);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3405, 'Datia', 401);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6991, 'Datia Nagar', 401);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7010, 'Deori', 421);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3453, 'Deori', 425);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3704, 'Deosar', 638);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3540, 'Depalpur', 410);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3437, 'Devendranagar', 420);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3526, 'Dewas', 402);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7031, 'Dewas Nagar', 402);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3662, 'Dhanora', 428);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3534, 'Dhar', 403);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3539, 'Dharampuri', 403);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3626, 'Dhimarkheda', 413);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7402, 'Dhulcot', 397);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7394, 'Dighora', 434);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3640, 'Dindori', 404);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3615, 'Dolariya', 409);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7422, 'Doraha', 427);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3544, 'Dr. Ambedkar Nagar (Mhow)', 410);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7419, 'Dudhamania', 638);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3635, 'Gadarwara', 418);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3591, 'Gairatganj', 421);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3535, 'Gandhwani', 403);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3450, 'Garhakota', 425);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3494, 'Garoth', 416);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3424, 'Gaurihar', 398);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3661, 'Ghansaur', 428);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7026, 'Ghatigaon', 407);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3511, 'Ghatiya', 435);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3602, 'Ghoda Dongri', 394);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3644, 'Ghughari', 415);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3432, 'Ghuwara', 398);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3399, 'Gird', 407);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3551, 'Gogaon', 414);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3395, 'Gohad', 395);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3593, 'Goharganj', 421);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6979, 'Gohparu', 429);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3699, 'Gopadbanas', 433);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7011, 'Gorakhpur', 411);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3394, 'Gormi', 395);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3634, 'Gotegaon', 418);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3578, 'Gulabganj', 437);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3520, 'Gulana', 430);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3677, 'Guna', 406);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6609, 'Guna Nagar', 406);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3438, 'Gunnor', 420);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3481, 'Gurh', 424);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7395, 'Gwalior Gramin', 407);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3577, 'Gyaraspur', 437);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3609, 'Handiya', 408);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3476, 'Hanumana', 766);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3608, 'Harda', 408);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3649, 'Harrai', 399);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3714, 'Harsud', 405);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3541, 'Hatod', 410);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3530, 'Hatpiplya', 402);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3454, 'Hatta', 400);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3614, 'Hoshangabad', 409);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7045, 'Hoshangabad Nagar', 409);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3581, 'Huzur', 396);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3479, 'Huzur', 424);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7041, 'Huzur Nagar', 424);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3586, 'Ichhawar', 427);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3404, 'Indergarh', 401);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3543, 'Indore', 410);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3684, 'Isagarh', 391);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3613, 'Itarsi', 409);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3631, 'Jabalpur', 411);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3459, 'Jabera', 400);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6984, 'Jaisinagar', 425);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3690, 'Jaisinghnagar', 429);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3695, 'Jaithari', 390);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3692, 'Jaitpur', 429);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3651, 'Jamai (Junnardeo)', 399);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3501, 'Jaora', 423);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3418, 'Jatara', 434);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3472, 'Jawa', 424);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3487, 'Jawad', 419);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3585, 'Jawar', 427);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3563, 'Jeerapur', 422);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3709, 'Jhabua', 412);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6983, 'Jharda', 435);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3553, 'Jhiranya', 414);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3490, 'Jiran', 419);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3712, 'Jobat', 639);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3388, 'Joura', 417);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3389, 'Kailaras', 417);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3523, 'Kalapipal', 430);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7012, 'Kanadia', 410);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3527, 'Kannod', 402);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3384, 'Karahal', 431);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3637, 'Kareli', 418);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3410, 'Karera', 432);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6533, 'Karkeli', 436);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3547, 'Kasrawad', 414);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3667, 'Katangi', 392);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7028, 'Katni Nagar', 413);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6980, 'Katthiwara', 639);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3663, 'Keolari', 428);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3452, 'Kesli', 425);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3508, 'Khacharod', 435);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3670, 'Khairlanji', 392);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3720, 'Khaknar', 397);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3715, 'Khalwa', 405);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3716, 'Khandwa', 405);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7019, 'Khandwa Nagar', 405);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3414, 'Khaniyadhana', 432);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3422, 'Khargapur', 434);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3550, 'Khargone', 414);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7029, 'Khargone Nagar', 414);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3531, 'Khategaon', 402);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3564, 'Khilchipur', 422);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3606, 'Khirkiya', 408);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7015, 'Khudel', 410);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6993, 'Khujner', 422);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3444, 'Khurai', 425);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7396, 'Killod', 405);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3673, 'Kirnapur', 392);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7034, 'Kolar', 396);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3411, 'Kolaras', 432);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3467, 'Kotar', 426);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3461, 'Kothi', 426);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7007, 'Kothi Mahal', 435);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3693, 'Kotma', 390);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3536, 'Kukshi', 403);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3681, 'Kumbhraj', 406);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3633, 'Kundam', 411);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3666, 'Kurai', 428);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3572, 'Kurwai', 437);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3702, 'Kusmi', 433);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3398, 'Lahar', 395);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3659, 'Lakhnadon', 428);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3671, 'Lalbarra', 392);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7399, 'Lamta', 392);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3676, 'Lanji', 392);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3570, 'Lateri', 437);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3425, 'Lavkush Nagar', 398);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6536, 'Lidhora', 434);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6987, 'Mada', 638);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7410, 'Madwas', 433);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3428, 'Maharajpur', 398);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3546, 'Maheshwar', 414);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3510, 'Mahidpur', 435);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3470, 'Maihar', 784);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3701, 'Majhauli', 433);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3462, 'Majhgawan', 426);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3628, 'Majholi', 411);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6995, 'Makdon', 435);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3616, 'Makhan Nagar', 409);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3680, 'Maksoodangarh', 406);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7014, 'Malharganj', 410);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3493, 'Malhargarh', 416);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3445, 'Malthon', 425);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3491, 'Manasa', 419);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3538, 'Manawar', 403);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3643, 'Mandla', 415);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3496, 'Mandsaur', 416);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7005, 'Mandsaur Nagar', 416);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3474, 'Mangawan', 424);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3484, 'Manpur', 436);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7000, 'Mau', 395);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3477, 'Mauganj', 766);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3708, 'Meghnagar', 412);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3393, 'Mehgaon', 395);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3397, 'Mihona', 395);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3419, 'Mohangarh', 434);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3655, 'Mohkhed', 399);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3521, 'Moman Badodiya', 430);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7038, 'Morar', 407);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3387, 'Morena', 417);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7047, 'Morena Nagar', 417);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3604, 'Multai', 394);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7411, 'Mundi', 405);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3688, 'Mungaoli', 391);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3620, 'Murwara Or Katni', 413);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3509, 'Nagda', 435);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3464, 'Nagod', 426);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3478, 'Naigarhi', 766);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3646, 'Nainpur', 415);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6973, 'Nai Sarai', 391);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3516, 'Nalkheda', 667);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3642, 'Narayanganj', 415);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3636, 'Narsimhapur', 418);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3568, 'Narsinghgarh', 422);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3409, 'Narwar', 432);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3575, 'Nateran', 437);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3489, 'Neemuch', 419);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7035, 'Neemuch Nagar', 419);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3721, 'Nepanagar', 397);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3560, 'Niwali', 393);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3415, 'Niwari', 722);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3641, 'Niwas', 415);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3427, 'Nowgong', 398);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3486, 'Nowrozabad', 436);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3416, 'Orchha', 722);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3569, 'Pachore', 422);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3420, 'Palera', 434);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3485, 'Pali', 436);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3632, 'Panagar', 411);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3718, 'Pandhana', 405);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3658, 'Pandhurna', 785);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3436, 'Panna', 420);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3559, 'Pansemal', 393);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3652, 'Parasia', 399);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3675, 'Paraswada', 392);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3629, 'Patan', 411);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3455, 'Patera', 400);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6971, 'Pathari', 437);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3457, 'Patharia', 400);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3555, 'Pati', 393);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3440, 'Pawai', 420);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3707, 'Petlawad', 412);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7412, 'Pichhor', 407);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3413, 'Pichhore', 432);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3618, 'Pipariya', 409);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3500, 'Piploda', 423);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7036, 'Piprai', 391);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7042, 'Pithampur', 403);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3407, 'Pohri', 432);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6511, 'Polaykala', 430);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3386, 'Porsa', 417);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7022, 'Prabhatpttan', 394);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3417, 'Prithvipur', 722);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3717, 'Punasa', 405);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3696, 'Pushparajgarh', 390);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3679, 'Raghogarh', 406);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7111, 'Raghurajnagar (Nagriya)', 426);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3448, 'Rahatgarh', 425);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3442, 'Raipura', 420);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3480, 'Raipur Karchuliyan', 424);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3590, 'Raisen', 421);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3565, 'Rajgarh', 422);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3430, 'Rajnagar', 398);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3558, 'Rajpur', 393);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7004, 'Rama', 412);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3469, 'Ramnagar', 784);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7032, 'Rampura', 419);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3466, 'Rampur Baghelan', 426);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3697, 'Rampur Naikin', 433);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3710, 'Ranapur', 412);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7025, 'Ranjhi', 411);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6976, 'Rannod', 432);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3506, 'Raoti', 423);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3507, 'Ratlam', 423);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7009, 'Ratlam Nagar', 423);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7016, 'Rau', 410);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3611, 'Rehatgaon', 408);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3451, 'Rehli', 425);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3589, 'Rehti', 427);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3621, 'Rithi', 413);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3396, 'Ron', 395);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3390, 'Sabalgarh', 417);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3449, 'Sagar', 425);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7030, 'Sagar Nagar', 425);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7003, 'Saikheda', 418);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3504, 'Sailana', 423);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6997, 'Sanawad', 414);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3542, 'Sanwer', 410);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6986, 'Sarai', 638);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3567, 'Sarangpur', 422);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3533, 'Sardarpur', 403);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7397, 'Satai', 398);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3528, 'Satwas', 402);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3656, 'Sausar', 785);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3548, 'Segaon', 414);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3582, 'Sehore', 427);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7008, 'Sehore Nagar', 427);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3475, 'Semaria', 424);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3561, 'Sendhwa', 393);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3403, 'Seondha', 401);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3664, 'Seoni', 428);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3612, 'Seoni Malwa', 409);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7018, 'Seoni Nagar', 428);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3687, 'Shadhora', 391);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3447, 'Shahgarh', 425);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3441, 'Shahnagar', 420);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3603, 'Shahpur', 394);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3630, 'Shahpura', 411);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3639, 'Shahpura', 404);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3519, 'Shajapur', 430);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3495, 'Shamgarh', 416);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3576, 'Shamshabad', 437);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3382, 'Sheopur', 431);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3408, 'Shivpuri', 432);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7044, 'Shivpuri Nagar', 432);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3522, 'Shujalpur', 430);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3583, 'Shyampur', 427);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3700, 'Sihawal', 433);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3627, 'Sihora', 411);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3596, 'Silwani', 421);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6975, 'Simariya', 420);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3488, 'Singoli', 419);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3705, 'Singrauli', 638);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7040, 'Singrauli Nagar', 638);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3607, 'Sirali', 408);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3473, 'Sirmour', 424);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3571, 'Sironj', 437);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3498, 'Sitamau', 416);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6977, 'Sleemnabad', 413);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3691, 'Sohagpur', 429);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3617, 'Sohagpur', 409);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6981, 'Sondawa', 639);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3525, 'Sonkatch', 402);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7421, 'Soyatkala', 667);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6532, 'Sultanpur', 421);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3515, 'Susner', 667);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6992, 'Suthaliya', 422);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3499, 'Suwasara', 416);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3503, 'Tal', 423);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3647, 'Tamia', 399);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7037, 'Tansen', 407);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3512, 'Tarana', 435);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3638, 'Tendukheda', 418);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3460, 'Tendukheda', 400);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3471, 'Teonthar', 424);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3706, 'Thandla', 412);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3556, 'Thikri', 393);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3423, 'Tikamgarh', 434);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3610, 'Timarni', 408);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3668, 'Tirodi', 392);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3524, 'Tonk Khurd', 402);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3574, 'Tyonda', 437);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3597, 'Udaipura', 421);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (6535, 'Udaynagar', 402);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3513, 'Ujjain', 435);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7046, 'Ujjain Nagar', 435);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3653, 'Umreth', 399);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3465, 'Unchehara', 426);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3562, 'Varla', 393);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3579, 'Vidisha', 437);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (7017, 'Vidisha Nagar', 437);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3380, 'Vijaypur', 431);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3624, 'Vijayraghavgarh', 413);
INSERT INTO sub_district (sub_district_id, sub_district_name, district_id) VALUES (3669, 'Waraseoni', 392);